### ISSUE TITLE
do you know from where to get data for https://boosters.pro/championship/data_fusion/overview

### ISSUE THREAD

**Issue by Sandy4321** [dremovd/data-fusion-2-baseline#1]
do you know from where to get data for https://boosters.pro/championship/data_fusion/overview

**Comment by dremovd** [comment]
A proper way to get competition data is to contact platform admins directly

**Comment by Sandy4321** [comment]
But how  find them

**Comment by dremovd** [comment]
This competition is from the boosters.pro platform.
They have an official telegram chat https://t.me/boosters
I also asked about their policy in general - if the dataset is no longer available on the platform it means that dataset owner asked them to delete the dataset after competition end, so there is no "right" way to get it.

The only chance is to ask several participants to share the dataset privately until somebody will agree. 
I prefer to comply with competition rules.
